model: "Point3R(Point3RConfig(pos_embed='RoPE100', pos_embed_3d='RoPE3D100', pose_head=True, img_size=(224, 224), head_type='dpt', output_mode='pts3d+pose', depth_mode=('exp', -inf, inf), conf_mode=('exp', 1, inf), pose_mode=('exp', -inf, inf), enc_embed_dim=1024, enc_depth=24, enc_num_heads=16, dec_embed_dim=768, dec_depth=12, dec_num_heads=12))"
pretrained: /mnt/data/wyq/WorkSpace/ckpt/DUSt3R_ViTLarge_BaseDecoder_512_dpt.pth
fixed_length: True
resume: null
benchmark: True
num_views : 5
n_corres_train: 0

train_criterion: ConfLoss(Regr3DPose(L21, norm_mode='?avg_dis'), alpha=0.2)

allow_repeat: False
data_root: "/mnt/data/wyq/WorkSpace/newbase/point3r_data_old" 
dataset1: Co3d_Multi(allow_repeat=${allow_repeat}, split='train', ROOT='${data_root}/processed_co3d/', aug_crop=16, resolution=224, transform=SeqColorJitter, num_views=${num_views}, n_corres=${n_corres_train})
dataset2: WildRGBD_Multi(allow_repeat=${allow_repeat}, split='train', ROOT="${data_root}/wildrgbd", aug_crop=16, resolution=224, transform=SeqColorJitter, num_views=${num_views}, n_corres=${n_corres_train})
dataset3: ARKitScenes_Multi(allow_repeat=${allow_repeat}, split='train', ROOT='${data_root}/processed_arkitscenes/', aug_crop=16, resolution=224, transform=SeqColorJitter, num_views=${num_views}, n_corres=${n_corres_train})
dataset4: ARKitScenesHighRes_Multi(allow_repeat=${allow_repeat}, split='train', ROOT="${data_root}/processed_arkitscenes_highres", aug_crop=16, resolution=224, transform=SeqColorJitter, num_views=${num_views}, n_corres=${n_corres_train})
dataset5: ScanNetpp_Multi(allow_repeat=${allow_repeat}, split='train', ROOT="${data_root}/processed_scannetpp/", aug_crop=16, resolution=224, transform=SeqColorJitter, num_views=${num_views}, n_corres=${n_corres_train})
dataset6: ScanNet_Multi(allow_repeat=${allow_repeat}, split='train', ROOT="${data_root}/processed_scannet/", aug_crop=16, resolution=224, transform=SeqColorJitter, num_views=${num_views}, n_corres=${n_corres_train})
dataset7: HyperSim_Multi(allow_repeat=${allow_repeat}, split='train', ROOT="${data_root}/hypersim", aug_crop=16, resolution=224, transform=SeqColorJitter, num_views=${num_views}, n_corres=${n_corres_train})
dataset8: BlendedMVS_Multi(allow_repeat=${allow_repeat}, split='train', ROOT="${data_root}/processed_blendedmvs/", aug_crop=16, resolution=224, transform=SeqColorJitter, num_views=${num_views}, n_corres=${n_corres_train})
dataset9: MegaDepth_Multi(allow_repeat=${allow_repeat}, split="train", ROOT="${data_root}/processed_megadepth", aug_crop=16, resolution=224, transform=SeqColorJitter, num_views=${num_views}, n_corres=${n_corres_train})
dataset10: Waymo_Multi(allow_repeat=${allow_repeat}, split=None, ROOT="${data_root}/waymo/", aug_crop=16, resolution=224, transform=SeqColorJitter, num_views=${num_views}, n_corres=${n_corres_train})
dataset11: VirtualKITTI2_Multi(allow_repeat=${allow_repeat}, split=None, ROOT="${data_root}/processed_vkitti", aug_crop=16, resolution=224, transform=SeqColorJitter, num_views=${num_views}, n_corres=${n_corres_train})


train_dataset: 10000 @ ${dataset1} + 10000 @ ${dataset2} + 10000 @ ${dataset3} + 10000 @ ${dataset4} + 10000 @ ${dataset5} + 10000 @ ${dataset6} + 5000 @ ${dataset7} + 10000 @ ${dataset8} + 10000 @ ${dataset9} + 10000 @ ${dataset10} + 5000 @ ${dataset11}

seed: 0
batch_size: 16
accum_iter: 1
epochs: 100
start_epoch: 0
weight_decay: 0.05
lr: 5e-5
min_lr: 1e-6
warmup_epochs: 5
amp: 1

num_workers: 24
world_size: 1
local-rank: -1
dist_url: 'env://'
rank: 0
gpu: 0
distributed: False
dist_backend: 'nccl'

save_freq: 1
keep_freq: 1
print_freq: 20
save_dir: 'checkpoints'
exp_name: 'stage1'
task: 'point3r'
logdir: ./${save_dir}/${exp_name}/logs
output_dir: ./${save_dir}/${exp_name}/
hydra:
  verbose: True
  run:
    dir: ./${save_dir}/${exp_name}